title: My Triathlon Journey
email: your-email@example.com
description: >-
  Documenting my training, challenges, and triumphs on the road to my triathlon.
baseurl: ""
url: ""
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Add this section to control the top menu:
header_pages:
  - about.md
  - why.md
